version: "3.9"

services:
  cass1:
    container_name: cass1
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_CLUSTER_NAME=BestCluster
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=1024M
  cass2:
    container_name: cass2
    image: cassandra:latest
    depends_on:
      - cass1
    environment:
      - CASSANDRA_SEEDS=cass1
      - CASSANDRA_CLUSTER_NAME=BestCluster
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=1024M
  cass3:
    container_name: cass3
    image: cassandra:latest
    depends_on:
      - cass1
    environment:
      - CASSANDRA_SEEDS=cass1
      - CASSANDRA_CLUSTER_NAME=BestCluster
      - HEAP_NEWSIZE=1M
      - MAX_HEAP_SIZE=1024M